PORTNAME=	macchina
DISTVERSIONPREFIX=	v
DISTVERSION=	6.2.1
CATEGORIES=	sysutils

MAINTAINER=	nxjoseph@protonmail.com
COMMENT=	System information frontend with an emphasis on performance
WWW=		https://github.com/Macchina-CLI/macchina

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cargo sqlite
USE_GITHUB=	yes
GH_ACCOUNT=	Macchina-CLI

PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
