PORTNAME=	dacite
DISTVERSIONPREFIX=	v
DISTVERSION=	1.8.1
CATEGORIES=	textproc python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nxjoseph@protonmail.com
COMMENT=	Simple creation of data classes from dictionaries
WWW=		https://github.com/konradhalas/dacite

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_GITHUB=	yes
GH_ACCOUNT=	konradhalas
USE_PYTHON=	autoplist distutils flavors

NO_ARCH=	yes

.include <bsd.port.mk>
