PORTNAME=	plexapi
DISTVERSION=	4.15.16
CATEGORIES=	multimedia python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nxjoseph@protonmail.com
COMMENT=	Python bindings for the Plex API
WWW=		https://github.com/pkkid/python-plexapi

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python:3.8+
USE_GITHUB=	yes
GH_ACCOUNT=	pkkid
GH_PROJECT=	python-plexapi
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes
NO_BUILD=	yes

.include <bsd.port.mk>
